### ISSUE TITLE
rhea2name.tsv file incomplete

### ISSUE THREAD

**Issue by isuen** [NCATS-Tangerine/rhea-beacon#3]
There are some RHEA ids that resulted in an error while getting their reaction name, and should be queried for again (found in `client\controller_impl\rhea2name_parsing` folder, any file ending with `_errors`)

Additional RHEA:14557 to 19162 does not have an error file, so there may be unrecorded missing RHEA ids between these two numbers

**Comment by lhannest** [comment]
We're using Rhea's SPARQL endpoint now, so this shouldn't be an issue.
