### ISSUE TITLE
Concept details for EC namespaces will return even if only partial EC number

### ISSUE THREAD

**Issue by isuen** [NCATS-Tangerine/rhea-beacon#5]
e.g. although EC:1 is not a distinct concept in of itself, /concepts/EC:1 will return a concept detail entry, 

This is because the method searches for EC:1 in the RHEA API, the API ignores the "EC:" part, and returns any results that contain "1" in it - these results are included in the related reactions comment

**Comment by lhannest** [comment]
Looks like it's been fixed, https://kba.ncats.io/beacon/rhea/concepts/EC:1 presently returns nothing.
